import { AgendaBlock } from '../types';

export function createGoogleCalendarUrl(
  title: string,
  details: string,
  location: string,
  startDateStr: string, // YYYYMMDDTHHmmssZ
  endDateStr: string
): string {
  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: title,
    details: details,
    location: location,
    dates: `${startDateStr}/${endDateStr}`
  });
  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

export function exportTokyoTripToGoogleCalendar(): string {
  // Master itinerary anchor event
  const title = 'SyncPass: Tokyo Bleisure (FinTech Summit + Coldplay Live)';
  const details = `Dual-track Bleisure Itinerary via SyncPass:
- Flight: SQ634 (SIN → HND)
- Business: Asia FinTech & AI Summit at Tokyo Big Sight (Aug 8-9)
- Entertainment: Coldplay Music of the Spheres at Tokyo Dome (Aug 10)
- Accommodation: Cerulean Tower Shibuya
- Leave Spent: 1 PTO day (Aug 8) anchored to SG National Day (Aug 9)
Generated by SyncPass Dual-Engine Calendar Intelligence.`;
  const location = 'Tokyo, Japan (Tokyo Big Sight & Tokyo Dome)';
  // 2025-08-08 08:00 to 2025-08-11 23:30 (UTC+9 JST => convert or format)
  return createGoogleCalendarUrl(title, details, location, '20250808T000000Z', '20250811T150000Z');
}

export function downloadTokyoIcsFile(agendaItems: AgendaBlock[]) {
  const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  
  let icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//SyncPass//Bleisure Schedule Optimizer//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'X-WR-CALNAME:SyncPass Tokyo Dual-Track Itinerary'
  ];

  agendaItems.forEach((item, index) => {
    // Generate dates based on dayIndex
    const dayMap = ['20250808', '20250809', '20250810', '20250811'];
    const dateStr = dayMap[item.dayIndex] || '20250808';
    const uid = `syncpass-tokyo-${item.id}-${index}@syncpass.app`;
    
    icsContent.push(
      'BEGIN:VEVENT',
      `UID:${uid}`,
      `DTSTAMP:${now}`,
      `DTSTART:${dateStr}T090000Z`,
      `DTEND:${dateStr}T170000Z`,
      `SUMMARY:[${item.category.toUpperCase()}] ${item.title}`,
      `DESCRIPTION:${item.subtitle}\\n\\n${item.notes || ''}\\n\\nGenerated by SyncPass`,
      `LOCATION:${item.venue}`,
      'STATUS:CONFIRMED',
      'END:VEVENT'
    );
  });

  icsContent.push('END:VCALENDAR');
  
  const blob = new Blob([icsContent.join('\r\n')], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', 'SyncPass_Tokyo_Master_Agenda.ics');
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
